spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/
queue.name=orders
spring.data.mongodb.uri=mongodb://localhost:27017/production-orders
spring.rabbitmq.listener.simple.acknowledge-mode=manual
# Dead Letter Exchange
spring.rabbitmq.listener.simple.dead-letter-exchange="dlx-exchange"
spring.rabbitmq.listener.simple.dead-letter-routing-key="dlx-queue.orders"
# Definir a fila DLX
spring.rabbitmq.listener.simple.queue-arguments.x-dead-letter-exchange="dlx-exchange"
spring.rabbitmq.listener.simple.queue-arguments.x-dead-letter-routing-key="dlx-queue.orders"
# Configuração da fila DLX
spring.rabbitmq.listener.simple.dlx.queue="dlx-queue.orders"