#
spring.output.ansi.enabled=always
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/
queue.name=orders
spring.data.mongodb.uri=mongodb+srv://kaiquemotta:${spring.data.mongodb.password}@production-orders.yrkxa.mongodb.net/${spring.data.mongodb.database}?retryWrites=true&w=majority&appName=production-orders
spring.data.mongodb.username=kaiquemotta
spring.data.mongodb.password=admin
spring.data.mongodb.database=production-orders
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.dead-letter-exchange="dlx-exchange"
spring.rabbitmq.listener.simple.dead-letter-routing-key="dlx-queue.orders"
spring.rabbitmq.listener.simple.queue-arguments.x-dead-letter-exchange="dlx-exchange"
spring.rabbitmq.listener.simple.queue-arguments.x-dead-letter-routing-key="dlx-queue.orders"
spring.rabbitmq.listener.simple.dlx.queue="dlx-queue.orders"