spring.application.name=production
spring.output.ansi.enabled=always
spring.rabbitmq.host=woodpecker.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=diehnoif
spring.rabbitmq.password=${RABBITMQ_PASSWORD:123}
spring.rabbitmq.virtual-host=diehnoif
queue.name=orders
