spring.application.name=production
spring.output.ansi.enabled=always
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
queue.name=orders
