name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'  # Usando a distribuição Adoptium (anteriormente adotopenjdk)

      - name: Build with Maven
        run: mvn clean install

      - name: Run application with RabbitMQ password from secrets
        env:
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}  # Usa o segredo configurado no GitHub
        run: java -jar target/your-application.jar
